Pipfile
Pipfile.lock
README.md
mergin/client.py
mergin/test/test_client.py
setup.py

with changed distribution of binaries

update to pygeodiff 0.3 

---

cli.py
mergin/client.py
mergin/test/test_client.py

added list of changes to project_status() method

#61 show list of changes

---

mergin/client.py
mergin/test/test_client.py

Overwriting geopackages is dangerous and should be avoided.
If a geopackage is open in some other client (and there are wal/shm files next to it),
it may loose data or even completely break the database file.

Try to fix sync issue in python client (#119)

---

mergin/client_pull.py
mergin/client_push.py
mergin/merginproject.py
mergin/test/test_client.py

1. Fix a problem when a pull of an empty project would break it
Initial download would save "v0" as the version, then pull was changing it to "" and afterwards push was crashing because it was expecting "v0"
2. Basic logging of sync process to .mergin/client-log.txt

Fix empty project pull + add basic logging

---

mergin/client.py
mergin/client_push.py
mergin/common.py
mergin/test/test_client.py

- create_project() only creates empty remote project, no uploads
- create_project_and_push() creates a project and does non-async upload
- username() new convenience method to get user name
- SyncError exception removed - we already have ClientError

API changes to better support project creation with async upload

---

mergin/client_push.py
mergin/merginproject.py
mergin/utils.py

When push finish was failing, the client was incorrectly returning as if there was no error.
+ added logging of checkpointing in sqlite files

Fix failing push finish

---

README.md
mergin/__init__.py
mergin/cli.py
mergin/client.py
mergin/client_pull.py
mergin/common.py
mergin/merginproject.py
setup.py

- cli.py gets installed as a 'mergin' command line tool
- client has default URL defined, so it's not needed to always set it
- if initial download fails, the newly created directory gets removed again (otherwise subsequent download would fail due to existing dir)
- handle DNS resolution error when doing requests
- download - will raise exception if project does not have fully qualified form "xxx/yyy"
- mergin client code does not raise basic Exception - instead uses module-specific classes
- all mergin exceptions defined in a single module

Random fixes to CLI and packaging improvements

---

.github/workflows/autotests.yml
mergin/test/test_client.py

Auto tests GitHub Actions job

---

.github/workflows/autotests.yml
README.md
mergin/client.py
mergin/client_push.py
mergin/test/test_client.py

Ownership depends on matching username with namespace, not ownership permissions.
closes #65

Check storage availability only for a project owned by a current user

---

mergin/cli.py
mergin/client.py
mergin/client_pull.py
mergin/test/test_client.py

Add option to download older versions of project

---

mergin/client_pull.py
mergin/merginproject.py

Fixes lutraconsulting/qgis-mergin-plugin#219
Improves logging during pull.

Fix pull error (failing update of basefile)

---

.github/workflows/autotests.yml

Error says:
```
HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```
Fix according to:
https://stackoverflow.com/questions/65692711/using-python-coveralls-from-github-actions-returns-could-not-submit-coverage-4

Try to fix coveralls github action that fails to upload results

---

mergin/cli.py
mergin/client.py
mergin/client_pull.py
mergin/merginproject.py
mergin/test/test_client.py

Fixes https://github.com/lutraconsulting/qgis-mergin-plugin/issues/191 
Also fixes invalid token type errors at MerginClient initialization: https://github.com/lutraconsulting/qgis-mergin-plugin/issues/186
I am still investigating how an invalid token would happen, but this should allow users for seamless token recreation in case it is invalid.
Also fixes https://github.com/lutraconsulting/qgis-mergin-plugin/issues/170 by proper logging file handler removal before deleting a Mergin project directory.

Auth token recreation

---

Pipfile
Pipfile.lock
mergin/client_pull.py
mergin/merginproject.py
mergin/test/test_client.py
setup.py

Closes https://github.com/lutraconsulting/mergin-py-client/issues/92 and https://github.com/lutraconsulting/mergin-py-client/issues/30

Make pygeodiff required for the client

---

mergin/client_push.py
mergin/merginproject.py
mergin/test/sqlite_con.py
mergin/test/test_client.py

New tests:
- when rebase is successful
- when rebase fails because local gpkg got schema changed
- when rebase fails because remote gpkg got schema changed
The tests are parametrized to check also the case when there is a pending
sqlite connection to gpkg (e.g. layer open in QGIS), to make sure things work
correctly in that case too (no sync failures / data corruption or loss).
Ensures that #96 and https://github.com/lutraconsulting/qgis-mergin-plugin/issues/246 are fixed now (thanks to fix for #30)

Add tests to verify that rebase is working correctly

---

mergin/client.py

Adds option to call user/service API and return response for python clients. 
This method is not exposed to CLI
Prerequisite for https://github.com/lutraconsulting/qgis-mergin-plugin/pull/311

Add call to user/service endpoint

---

mergin/merginproject.py

When a file has some special unicode characters in its name (ex: é), logging cannot write the corresponding log message (ex: Message: 'Downloading filewithunicode.gpkg version=vXXX diff=False part=0') to the log file and it prints a massive error message to the terminal. 
Solution suggested is to add utf8 to the encoding parameter of logging FileHandler
`--- Logging error ---
Traceback (most recent call last):
File "C:\Users\hp\anaconda3\envs\mm\lib\logging\__init__.py", line 1086, in emit
stream.write(msg + self.terminator)
File "C:\Users\hp\anaconda3\envs\mm\lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0301' in position 58: character maps to <undefined>
Call …

prevent logging errors with unicode

---

mergin/merginproject.py

Move geodiff-related code from `apply_pull_changes` to new methods which update versioned file with or without rebase.
Fix #116.

Refactor apply_pull_changes

---

mergin/client_pull.py

This is to avoid mismatch of actual size of downloaded file and original size that server created.
The reason for mismatch is that if gpkg file is reconstructed on server using geodiff changesets it can eventually has a different size than original file (removed for space optimization).
closes #119

Do not check file size for server-reconstructed gpkg file

---

mergin/client.py
mergin/client_pull.py
mergin/merginproject.py
mergin/test/test_client.py
mergin/utils.py

Apply new naming scheme for conflict files:
-   `my data (conflicted copy, martin v10).gpkg` - for full copy (when rebase fails)
-   `my data (edit conflict, martin v10).json` - for list of edit conflicts upon rebase (always a JSON file)
Fixes #62.

use unique file names for conflict files (fixes #62)

---

mergin/client.py
mergin/client_pull.py
mergin/client_push.py
mergin/merginproject.py
mergin/test/test_client.py

Implement approach described in #117.
If the rebase fails and copy of the database file fails too (common on Windows), keep an extra directory `unfinished_pull` inside `.mergin` dir with the files we need to copy but we were unable to do because the files were locked by OS.
New methods added:
- `has_unfinished_pull` - checks whether there is an unfinished pull
- `resolve_unfinished_pull` - try to apply changes from unfinished pull

Handle rebase failure (refs #117)

---

mergin/client_pull.py
mergin/client_push.py

Wrap `apply_pull/push_changes()` into `try...except` to catch possible exceptions. Fixes #103.

caught exceptions which might occur during pull or push and log them properly (fix #103)

---

mergin/cli.py
mergin/client.py
mergin/client_pull.py
mergin/merginproject.py

In case when pull failed and project was left in the unfinished pull state we will try to resolve this situation on the next pull. But user should also be able to do this manually. For this purpose a new command `resolve-unfinised-pull` added to the command-line tool.

Add new command to cli tool to resolve unfinished pull

---

mergin/client.py
mergin/client_pull.py
mergin/merginproject.py
mergin/report.py
mergin/test/test_client.py

This PR adds reporting functionality to export changesets aggregates for mergin projects in given version range to a csv file. It is a prerequisite for https://github.com/lutraconsulting/qgis-mergin-plugin/issues/337 to be wrapped in processing tools in QGIS. If used outside of mergin plugin, calculation of features lengths/areas will not be available.
PR also adds caching option for downloading diff files into .mergin folder, so the same files do not need to be downloaded again.
PR also modifies `project_versions` function to use paginated version of server endpoint. Non-paginated endpoints are deprecated on server and will be removed.
Possible enhancements in future:
- run processing/reporting of files in parallel
- create progress bar

Report tool

---

mergin/client.py
mergin/merginproject.py

This allows to maintain the same behavior as in case of normal pull, e.g. if there are conflicts we can ask user to examine them

return list of conflict files when resolving unfinished pull

---

mergin/client.py
mergin/client_push.py
mergin/test/test_client.py

As described in lutraconsulting/qgis-mergin-plugin#351 when user who is not an owner of the organization tries to sync project of the organization they get error. It happens because client relies on the `access` field of the project information to determine whether user has write permissions on a given project. However `access` field is taken from the explicit project permissions, while invited to the organization users get access via this organization.
In order to overcome this issue we need to check write access using `permissions` field, as this field is evaluated with respect to namespace.
Refs lutraconsulting/qgis-mergin-plugin#351
Refs CU-28km50n

check user permissions using "permissions" field

---

mergin/test/test_client.py
mergin/utils.py

As discussed in https://github.com/lutraconsulting/qgis-mergin-plugin/issues/382 add `~` at the end of the conflicted copy if this is a QGIS project file.

add special handling for the names of the conflicted files for QGIS project files

---

mergin/client.py
mergin/client_pull.py
mergin/test/test_client.py

Fixes a couple of unreported issues related to downloading of files/changesets:
- passing `None` to `download_file()` method to indicate that the latest version of the file is requested does not work correctly. We have to pass actual version, otherwise server will return an error
- downloading of concatenated diff with `get_file_diff()` method does not work if some changesets were already cached. They are excluded from the download and never taken into account. As a result `get_file_diff()` fails to create an output diff.

Fix issues with files and changesets downloading

---

mergin/cli.py

Fix broken status and download-file in CLI

---

.gitignore
README.md
mergin/cli.py
mergin/client.py
setup.py

fix #21
also added bunch of extra filters:
```
Usage: mergin list-projects [OPTIONS]
List projects on the server.
Options:
--flag TEXT          What kind of projects (e.g. 'created' for just my
projects,'shared' for projects shared with me. No flag
means returns all public projects.
--name TEXT          Filter projects with name like name
--namespace TEXT     Filter projects with namespace like namespace
--order_params TEXT  optional attributes for sorting the list.It should be a
comma separated attribute nameswith _asc or _desc
appended for sorting direction.For example:
"namespace_asc,disk_usage_desc".Available attrs:
namespace, name, created, updated, disk_usage, creator
--help               Show this message and exit.
```

list projects for more > 50

---

mergin/merginproject.py

Add new method to `MerginProject` class to set list of tables which should be exculded from geodiff operations.
Requires geodiff with https://github.com/MerginMaps/geodiff/pull/182

add method for defining list of tables to ignore from geodiff operations

---

mergin/client.py
mergin/client_pull.py
mergin/client_push.py
mergin/test/test_client.py

Added project ID to the local project metadata.
Changes required for fixing db-sync issue: https://github.com/MerginMaps/mergin-db-sync/issues/76

Added project ID to the metadata.

---

mergin/client.py

`def global_namespace(self):` will be redundant with the upcoming API changes as this info should be available by `/workspaces` endpoint and CE and EE versions will be treated the same.

Workspaces

---

mergin/client.py
mergin/client_push.py
mergin/test/test_client.py

we let the server handle it instead
rework related tests

remove space available check on upload

---

mergin/client.py
mergin/test/test_client.py
mergin/utils.py

- Added `create_workspace` function to API so that test users can create their workspace (if does not have yet)
- Removed check for organisation project (used to be some predefined project in test.dev)
Note: tests that failed are those that usually fail in a feature branch - we need to address this, but let's not do it now.

Fix autotests now with workspaces server

---

mergin/cli.py
mergin/client.py
mergin/test/test_client.py

Use paginated versions endpoint instead of removed endpoint.
Fixes #167

Fix project version info

---

mergin/client.py
mergin/client_push.py
mergin/merginproject.py
mergin/test/test_client.py

In `MerginProject` method `get_push_changes()` check for zero size diff files and removes them.
In `MerginClient`  method `push_project()` clean any existing diff files when the method ends. 
Fixes #47

Remove diff files

---

README.md
mergin/cli.py

Currently the hint for setting the variable works in Linux and confuses Windows users.
Suggested solution is to suggest a valid system-dependent hint.

Add hint for setting MERGIN_AUTH variable in Windows

---

mergin/client.py
mergin/test/test_client.py

Previously we would only get the detail (e.g. `The requested URL was not found on the server.`) but there would be no information on what URL was actually accessed. This PR adds more info: URL, method and http error code (+reason)

Improve how HTTP errors are reported as client errors

---

mergin/client.py
mergin/test/test_client.py
mergin/utils.py

Newer server versions started to use scheduled delete, which broke the tests, because it was not possible to re-create the same projects earlier than in a couple of days.

Add immediate project removal to fix auto-tests

---

mergin/cli.py
mergin/client.py
mergin/client_pull.py
mergin/client_push.py
mergin/merginproject.py
mergin/report.py
mergin/test/test_client.py

This is to make the code more clear about what data it gets from metadata, and also to be ready for future when we change the way how metadata are stored.

Use explicit function calls to get project metadata

---

mergin/client.py
mergin/test/test_client.py

Make `project_info()` function accept either project ID or full project name to get project info.
Fixes #179.

allow querying project information by project ID (fix #179)

---

mergin/cli.py

Fixes #172
Makes namespace argument of `mergin list-projects` which should avoid listing way to much projects and thus hanging the tool.

change namespace from option to argument

---

mergin/client.py
mergin/client_pull.py
mergin/test/test_client.py

Introduce reset_local_changes()

---

mergin/client_pull.py
mergin/test/test_client.py

When project download fails for some reason we remove project directory and raise an exception. This exception than catched in the plugin and error message is shown. However, in some cases (namely, when unexpected error occurs) this message is very basic and it is hard to say what is going on.
The support team proposed that we keep log file as it might contain useful information and provide an option in the plugin to send that log to developers. To make this possible in the client we create a copy of the log file in the system temporary directory before cleaning up failed download. The path to the log file is added to the exception as an attribute and can pluign can check for it and act accordingly.
Fixes #155 
Fixes #156

copy log file to the temp dir before removing project directory

---

.gitignore
mergin/cli.py
mergin/client.py
mergin/test/test_client.py

**Features**
- added editor permission
- check compatibility with "old" servers (before 2024.4) and editor support (ignore editorsnames lists in project sharing)
- If users are trying to use "edit" permission with "old" servers, exception is raised
- Tests are compatible with all servers versions:
- - Test run with "old" test.dev without editor permission - https://github.com/MerginMaps/python-api-client/actions/runs/9171423484
-- Test run with  2024.4.0 test.dev with editor support - https://github.com/MerginMaps/python-api-client/actions/runs/9172108349/job/25217898845
:exclamation: 
- release after server release :)

Added editor project permission

---

mergin/client_pull.py

Some users were getting this exception while handling download error:
```
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
```
Reported here: https://github.com/MerginMaps/qgis-plugin/issues/573 and https://github.com/MerginMaps/qgis-plugin/issues/578

Fix call to format_exception() download project fails

---

mergin/editor.py
mergin/test/test_client.py

Relates to https://github.com/MerginMaps/qgis-plugin/issues/581#issuecomment-2172527072
**Details**
- filter **only** updates of qgis files from changes and conflicted copy
There were implemented all editors rules. We want filter out just qgis files changes (updated), because it should not be controlled by user.

Filter only qgis files for editor

---

.github/workflows/autotests.yml
mergin/client.py
mergin/common.py
mergin/test/test_client.py
mergin/utils.py

This PR improve the ClientError exception to make it easier to parse and return feedback to user.  Instead of relying on a text based error we define variable member of the ClientError Exception than will hold the data response from the server. 
Used only for the qgis-plugin for now

Improve ClientError  handling

---

mergin/cli.py
mergin/client.py
mergin/test/test_client.py

Resolves #214 
Changes:
- CLI: update show version command to call project_version_info object
- CLIENT: upgrade project_version_info api call to use get byt version name endpoint instead of paginated version
- TEST: don't use paginated endpoint in tests
- TEST: make tests runnable with other username, than test_plugin 
Fix :bug: 
- There was Error in CLI, If you asked version number (e.g. v1) ```Detail: Wrong type, expected 'integer' for query parameter 'page'``` - show-version was not running properly.
Minor:
- add year to copyright :)
Related to: https://github.com/MerginMaps/server/pull/275/files

Do not use paginated versions endpoint

---

README.md
mergin/cli.py

Add a list-files command, with optional JSON output.
`$ mergin list-files mergin/simplebees`
```python
Usage: mergin list-files [OPTIONS] PROJECT
List files in a project.
Options:
--json  Output in JSON format
--help      Show this message and exit.
```
```bash
$ mergin list-projects
List of projects (all public):
Fetched 9 projects .
mergin / pgv                            	   0.1 MB	v6
mergin / databank                       	   0.7 MB	v7
$ mergin list-files mergin/databank
Fetched 8 files .
databank.qgz                            	   0.0 MB
Survey_points.gpkg                      	   0.1 MB
datas/2-Survey_points.gpkg              	   0.1 MB
datas/0-Survey_points.gpkg              	   0.1 MB
datas/3-Survey_points.gpkg              	   0.1 MB
datas/4-Survey_points.gpkg …
```

add list-files command

---

mergin/cli.py
mergin/client_pull.py
mergin/client_push.py
mergin/merginproject.py
mergin/test/test_client.py
setup.py

Changes all previous reference to the current repository to `python-api-client`instead of `mergin-py-client`
No  functional changes

Cleanup references to previous repository name of python-api-client

---

mergin/client.py
mergin/test/test_client.py

This is first usage of testing API for changing storage limits and projects count. Test for storage and project limit hit are now using new api. There is also ```test_available_storage_validation2``` but no validation is performed here (we need to name or remove in future). 
Other :heavy_plus_sign: 
- add patch to mergin client

Implementing testing api for storage change to limits tests

---

mergin/common.py
mergin/test/test_client.py

In order to achieve [PR](https://github.com/MerginMaps/qgis-plugin/pull/640) for [issue](https://github.com/MerginMaps/qgis-plugin/issues/643), we need to support `MonthlyContributorsLimitHit` in py-client.

Support for MonthlyContributorsLimitHit error

---

mergin/client.py
mergin/client_pull.py
mergin/report.py
mergin/test/test_client.py

This PR is required to support the history viewer in the QGIS as part of MerginMaps/qgis-plugin/pull/630
This PR contains: 
*  update and add functions to fetch history information (pagination, range count)
* Add a function to know the workspace usage right

Project history : Add functionnalities for the  version viewerin the QGIS plugin

---

mergin/client.py

This PR contain two cleanup
* Remove unused user_service since get_user_service was deprecated and return http 400 
see https://github.com/MerginMaps/server-private/blob/7edf64b43b04bf017c8c555f913f6d8c3b0d7441/server/src/service/api.yaml#L42
* Handle error in  `mc.workspace_service` by re raising a ClientError
Needed to cleanup in the plugin PR https://github.com/MerginMaps/qgis-plugin/pull/650

Cleanup: Remove deprecated function and improve error handling

---

mergin/cli.py
mergin/client.py
mergin/test/test_client.py

This check has been forgotten for some time now and blocks us from cleaning up the `/ping` response.
The PR removes it altogether as it had no use now 🙃

Remove deprecated check for server compatibility via the list of endpoints

---

mergin/client.py
mergin/test/test_client.py

There is a typo in my last PR regarding the use of json module 
I used `json.loads` with a `s` instead of `json.load` that support de serializing python object and not string
Every use of workspace_service failed in the plugin because of that

Fail in last PR regarding the use of json module

---

mergin/common.py
mergin/test/test_client.py

This PR partially reverse 74222e4 to only remove the change related to the monthly contributor (e.g: error)

Partial reverse of 74222e4 to remove the monthly contributor error dialog

---

examples/README.md

Noticed some typos in the readme file for Jupyter notebooks examples - please check this out :)

Jupyter notebooks - Update README.md

---

mergin/client.py
mergin/test/test_client.py

Allow creation of MerginClient without login.
Add test case that MC without login can get server config but cannot do much else.

allow client creation without authorization

---

mergin/client.py
mergin/test/test_client.py

Fixes how `HTTPError` is handled in `_do_request()`.
This should fix a lot of errors in plugin and db-sync, or at least provide much better error messages for them.
Fixes MerginMaps/qgis-plugin#642 and many others

Fix error handling  _do_request()

---

mergin/client.py
mergin/common.py

Fix sending logs using POST method.

Fix logs sending

---

mergin/client.py
mergin/merginproject.py

A step to understand https://github.com/MerginMaps/qgis-plugin/issues/804
Remove duplicate logging
Add meaningful logging.

Add auth logging

---

mergin/client.py
mergin/test/test_client.py

Fixes https://github.com/MerginMaps/qgis-plugin/pull/815#issue-3437479877
Fixes https://github.com/MerginMaps/python-api-client/issues/279

Return OLD server only for 404 resp
