- .gitignore
- README.md
- mergin/client.py
- setup.py
This fixes issue with gunicorn which needs Content-Length even for stream requests.
> Used MultipartEncoder from requests_toolbelt to include Content-Length

- CHANGELOG.md
- README.md
- cli.py
- mergin/client.py
- mergin/utils.py
- setup.py
Files are uploaded using serve API transactional uploads. Files' chunks are sent sequentially. 
Also contains small auth fixes and remove project function (for easier testing).
> Upload revisited

- cli.py
- mergin/client.py
Allows to create blank project on server.
Prerequisite for https://github.com/lutraconsulting/qgis-mergin-plugin/issues/32
> optional project directory when creating new project

- cli.py
- mergin/client.py
Added support for parallel request for download and upload. Used as default. Previous sequential is also supported (for testing purposes).
closes #9
> Added multithreaded (parallel) upload and download to speed up sync

- cli.py
- mergin/client.py
> added check for minimal set of server endpoints 

- README.md
- cli.py
- mergin/client.py
- mergin/test/test_client.py
closes #24, prerequisite for https://github.com/lutraconsulting/qgis-mergin-plugin/issues/15
> added project status function

- Pipfile
- Pipfile.lock
- mergin/client.py
- setup.py
adopted to changes in api - geodiff.apply_changeset
> update to pygeodiff 0.6 

- Pipfile
- Pipfile.lock
- README.md
- mergin/client.py
- setup.py
to avoid copying files at pull cmd as much as possible
> update to geodiff version with rebase function 

- Pipfile.lock
- mergin/client.py
closses #25 from qgis-mergin-plugin repository
> #25 warning when no free space left

- mergin/client.py
> Add user agent header to request#31

- mergin/client.py
relates to issue #80 from mergin-plugin
> fix problem with download files with zero size

- mergin/client.py
relates to mergin plugin issue https://github.com/lutraconsulting/qgis-mergin-plugin/issues/99
> ResourceWarning: unclosed file fix by use with

- mergin/client.py
- mergin/test/test_client.py
(relates #106 mergin plugin issue)
> added details about request to exception if create project failed

- Pipfile
- mergin/client.py
- mergin/test/test_client.py
- setup.py
(relates #108 mergin plugin issue)
> expired token handle

- mergin/client.py
relates to mergin-plugin, closes https://github.com/lutraconsulting/qgis-mergin-plugin/issues/115
> added check if size of downloaded file is same as size file the server

- Pipfile.lock
- mergin/cli.py
- mergin/merginproject.py
- mergin/test/test_client.py
push "removed" and "added" ones instead 
/closes #27
> disable upload of renamed files

- mergin/client.py
QUESTION: Do we want to keep `namespace` as it is now, so if is not defined, a username is taken or do we want to have it required?
> Add namespace argument to the create_project function

- mergin/cli.py
- mergin/client.py
- mergin/test/test_client.py
> Added project cloning

- Pipfile.lock
- mergin/client.py
- mergin/test/test_client.py
This PR adds support for new endpoint `v1/project/by_names` for bulk query of projects' info.
> Add support for endpoint to get projects by names

- mergin/client.py
This is also for https://github.com/lutraconsulting/qgis-mergin-plugin/issues/229
> Raise URLError with a sensible message

- mergin/merginproject.py
Fixes https://github.com/lutraconsulting/qgis-mergin-plugin/issues/232
> Handled removing non-existing local files

- mergin/test/test_client.py
See https://github.com/lutraconsulting/mergin-py-client/pull/84
> Added a test for handling locally missing files.

- .gitignore
- mergin/client_pull.py
- mergin/client_push.py
- mergin/test/test_client.py
Also added logging for download/pull.
Fixes https://github.com/lutraconsulting/qgis-mergin-plugin/issues/231
> Proper cancelling and logging of push jobs with a test

- mergin/client.py
Preliminary fix for https://github.com/lutraconsulting/qgis-mergin-plugin/issues/123
> Support for HTTP proxy

- mergin/client_push.py
Not related to any ticket - found while fixing other Python warnings for Mergin QGIS plugin.
> Fixed Python warnings about unclosed resources

- README.md
- mergin/cli.py
- mergin/client.py
Added project creation for a specified namespace.
Fixed project removal.
Closes #76
Closes #81 
Closes #82
Closes #95
> Login improvements and other CLI fixes

- .github/workflows/autotests.yml
- README.md
- mergin/cli.py
- mergin/client.py
- mergin/client_pull.py
- mergin/merginproject.py
- mergin/test/test_client.py
- mergin/utils.py
And do some "Mergin" → "Mergin Maps" replacements.
>  update public and test server URL's

- .github/workflows/autotests.yml
Use coveralls github action instead manual pushing. Fix the unhandled error.
> Trying to fix coveralls

- mergin/client_pull.py
Reverts MerginMaps/python-api-client#253
Just preparation for release when temp files location in local machines #259
> Revert "Store pull files in temp directory"
